### ISSUE TITLE
Breath emissions calculation

### ISSUE THREAD

**Issue by rs028** [DrDaveShaw/INCHEM-Py#18]
Could you detail here the bug in the calculation of breath emissions that you mentioned to me a while ago? I have some time available and I can try to fix it (if it is not too complicated!)

**Comment by DrDaveShaw** [comment]
The breath emissions are input according to [this table](https://gmd.copernicus.org/articles/16/7411/2023/#Ch1.T1). The values were taken from [Kruza and Carslaw (2019)](https://doi.org/10.1111/ina.12539) which were calclated in a 171 m3 room. The emission therefore needs to be adjusted to the volume of the room being modelled, essentially multiplied by the 171 m3 and divided by the volume of the simulated room.

I am hoping to push an update soon where we will have volume and surface area input seperately, instead of having just an A/V input.

**Comment by rs028** [comment]
So that means simply adding to the following bit a division by 1.71e8 cm3?

```
def breath_emissions():
    breath_rates = [
    #
    #Breath
    ['EMISSIONBREATHACETONE','(2.534e+07*adults)+(4.781e+6*children)'],
    ['EMISSIONBREATHETHANOL','(1.988e7*adults)+(3.009e6*children)'],
    ['EMISSIONBREATHMETHANOL','(8.512e6*adults)+(3.108e6*children)'],
    ['EMISSIONBREATHISOPROPANOL','(3.862e6*adults)+(6.593e5*children)'],
    ['EMISSIONBREATHISOPRENE','(5.412e6*adults)+(5.953e5*children)'],
    ]
```

as in:

`['EMISSIONBREATHACETONE','((2.534e+07*adults)+(4.781e+6*children))/1.71e-8'],`

etc... and that would solve the issue?

**Comment by DrDaveShaw** [comment]
Not quite as then you need to adjust the emission for the volume of the room. I am just about the push an update to fix this issue by having the volume and surface areas as inputs rather than just the surface to volume ratios.

**Comment by rs028** [comment]
Ah brilliant, thank you!

**Comment by rs028** [comment]
Wait, shouldn't it be 1.71e8 instead of 171e8?

**Comment by DrDaveShaw** [comment]
Yes....oops
