### ISSUE TITLE
Recursion error

### ISSUE THREAD

**Issue by Lyko0c0** [DrDaveShaw/INCHEM-Py#19]
Settings.py is not running. There is some issue with the initial_directories.py and i get the RecursionError: maximum recursion depth exceeded during compilation.
 
`File ~\INCHEM-Py-main\modules\initial_dictionaries.py:219 in master_compiler
    master_compiled[i]=compile(y,'<string>','eval',)

RecursionError: maximum recursion depth exceeded during compilation`

I tried the most common fixes but nothing seems to work

**Comment by DrDaveShaw** [comment]
Thank you for reporting the error. 

The recursion limit set by Python is usually 1000 but is known to be rather conservative so in /modules/inchem_main.py:62 (in v1.2) sets the recursion limit to 4000 which is enough to cover the chemistry input by the MCM and the additional INCHEM-Py chemical schemes when creating the master_array (the array of ODE's that gets solved). 

Are you adding any extra chemical schemes or reactions, for example through the custom input? 

If you increase the recursion limit do you still get the same issue? 

I will look into making the master_compiler function more efficient.

**Comment by Lyko0c0** [comment]
I tried various limits but nothing seemed to work. I havent added anything at the moment i'm just trying to run the default file.
________________________________
Από: DrDaveShaw ***@***.***>
Στάλθηκε: Παρασκευή, 12 Ιουλίου 2024 4:53 πμ
Προς: DrDaveShaw/INCHEM-Py ***@***.***>
Κοιν.: Lyko0c0 ***@***.***>; Author ***@***.***>
Θέμα: Re: [DrDaveShaw/INCHEM-Py] Recursion error (Issue #19)


Thank you for reporting the error.

The recursion limit set by Python is usually 1000 but is known to be rather conservative so in /modules/inchem_main.py:62 (in v1.2) sets the recursion limit to 4000 which is enough to cover the chemistry input by the MCM and the additional INCHEM-Py chemical schemes when creating the master_array (the array of ODE's that gets solved).

Are you adding any extra chemical schemes or reactions, for example through the custom input?

If you increase the recursion limit do you still get the same issue?

I will look into making the master_compiler function more efficient.

**Comment by DrDaveShaw** [comment]
I'm not sure why the change in the recursion limit doesn't appear to be working.

One thing that I have noticed is that the line given in your error doesn't correspond to the line that is giving the error in the module. Also the ` '<string>'` section of the compile is missing. My only suggestion at this stage is to delete the model, re-download the v1.2 release and try again. If this produces an error then please send me the entire output.

Apologies that you're having trouble running the model, it's the first time I have seen this as an issue since I implemented the recursion limit increase.

**Comment by DrDaveShaw** [comment]
@Lyko0c0 did you manage to get the model to run?
